name: C++ Test Workflow

on:
  push:
    branches:
      - feature/m00ex02
  pull_request:
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          cmake -S Modules/Module00/ex02/test -B build
          cmake --build build

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure --verbose